repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: system
      - id: ruff
        name: ruff
        entry: ruff . --fix
        language: system
        types_or: [python, pyi]
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
