repos:
  - repo: local
    hooks:
      - id: ruff_lint
        name: ruff (lint)
        entry: ruff check . --fix
        language: system
        types_or: [python]
      - id: ruff_format
        name: ruff (format)
        entry: ruff format .
        language: system
        types_or: [python]
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
