[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore-init-module-imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = [
    "pooltool",
]

[tool.pyright]
include = [
    "pooltool",
]
ignore = [
  "pooltool/ani",
]
exclude = [
  "**/test_*",
  "**/render.py",
  "**/__pycache__",
]

