name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # --- Pytest

    - name: Pytest
      id: pytest
      continue-on-error: true
      run: |
        pytest

        status=$?
        if [ $status -ne 0 ]; then
          echo "Pytest failed with status $status"
          echo "::set-output name=pytest_failed::true"
        fi

    # --- Pyright

    - name: Pyright
      id: pyright
      continue-on-error: true
      run: |
        pyright --project ./pyrightconfig.ci.json

        status=$?
        if [ $status -ne 0 ]; then
          echo "Pyright failed with status $status"
          echo "::set-output name=pyright_failed::true"
        fi

    # --- Ruff

    - name: Ruff
      id: ruff
      continue-on-error: true
      run: |
        ruff check .

        status=$?
        if [ $status -ne 0 ]; then
          echo "Ruff failed with status $status"
          echo "::set-output name=ruff_failed::true"
        fi

    # --- isort

    - name: isort
      id: isort
      continue-on-error: true
      run: |
        isort . --check-only

        status=$?
        if [ $status -ne 0 ]; then
          echo "isort failed with status $status"
          echo "::set-output name=isort_failed::true"
        fi

    # --- Main

    - name: Test results
      if: always()
      run: |
        passed=()
        failed=()

        # --- Add all test outputs here {{{

        if [[ "${{ steps.pytest.outputs.pytest_failed }}" == "true" ]]; then
          failed+=("pytest")
        else
          passed+=("pytest")
        fi

        if [[ "${{ steps.pyright.outputs.pyright_failed }}" == "true" ]]; then
          failed+=("pyright")
        else
          passed+=("pyright")
        fi

        if [[ "${{ steps.ruff.outputs.ruff_failed }}" == "true" ]]; then
          failed+=("ruff")
        else
          passed+=("ruff")
        fi

        if [[ "${{ steps.isort.outputs.isort_failed }}" == "true" ]]; then
          failed+=("isort")
        else
          passed+=("isort")
        fi

        # --- }}}

        if [ ${#passed[@]} -ne 0 ]; then
          echo "PASSED:"
          for check in "${passed[@]}"; do
            echo "    - $check"
          done
        fi

        if [ ${#failed[@]} -ne 0 ]; then
          echo "FAILED:"
          for check in "${failed[@]}"; do
            echo "    - $check"
          done
          exit 1
        fi
