name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Choose the Python version you need
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Pytest
      run: pytest
      continue-on-error: true

    - name: Check formatting complies with Black
      run: |
        ruff check .
      continue-on-error: true

    - name: Check import order complies with isort
      run: |
        isort . --check-only
      continue-on-error: true

    - name: Run Pyright type checking
      run: pyright --project ./pyrightconfig.ci.json
      continue-on-error: true
