name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # --- Pytest

    - name: Pytest
      id: pytest
      run: pytest

    - name: Set failed output for Pytest
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: echo "::set-output name=pytest_failed::true"

    # --- Pyright

    - name: Pyright
      id: pyright
      run: pyright --project ./pyrightconfig.ci.json

    - name: Set failed output for Pyright
      if: ${{ steps.pyright.outcome == 'failure' }}
      run: echo "::set-output name=pyright_failed::true"

    # --- Ruff

    - name: Ruff
      id: ruff
      run: ruff check .

    - name: Set failed output for Ruff
      if: ${{ steps.ruff.outcome == 'failure' }}
      run: echo "::set-output name=ruff_failed::true"

    # --- isort

    - name: isort
      id: isort
      run: isort . --check-only

    - name: Set failed output for isort
      if: ${{ steps.isort.outcome == 'failure' }}
      run: echo "::set-output name=isort_failed::true"

    # --- Main

    - name: Test results
      if: always()
      run: |
        passed=()
        failed=()

        # --- Add all test outputs here {{{

        if [[ "${{ steps.pytest.outputs.pytest_failed }}" == "true" ]]; then
          failed+=("pytest")
        else
          passed+=("pytest")
        fi

        if [[ "${{ steps.pyright.outputs.pyright_failed }}" == "true" ]]; then
          failed+=("pyright")
        else
          passed+=("pyright")
        fi

        if [[ "${{ steps.ruff.outputs.ruff_failed }}" == "true" ]]; then
          failed+=("ruff")
        else
          passed+=("ruff")
        fi

        if [[ "${{ steps.isort.outputs.isort_failed }}" == "true" ]]; then
          failed+=("isort")
        else
          passed+=("isort")
        fi

        # --- }}}

        if [ ${#passed[@]} -ne 0 ]; then
          echo "PASSED:"
          for check in "${passed[@]}"; do
            echo "    - $check"
          done
        fi

        if [ ${#failed[@]} -ne 0 ]; then
          echo "FAILED:"
          for check in "${failed[@]}"; do
            echo "    - $check"
          done
          exit 1
        fi
