name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    # --- Pytest

    - name: Pytest
      id: pytest
      continue-on-error: true
      run: |
        pytest
        echo "pytest_failed=$?" >> $GITHUB_ENV

    # --- Pyright

    - name: Pyright
      id: pyright
      continue-on-error: true
      run: |
        pyright --project ./pyrightconfig.ci.json
        echo "pyright_failed=$?" >> $GITHUB_ENV

    # --- Ruff

    - name: Ruff
      id: ruff
      continue-on-error: true
      run: |
        ruff check .
        echo "ruff_failed=$?" >> $GITHUB_ENV

    # --- isort

    - name: isort
      id: isort
      continue-on-error: true
      run: |
        isort . --check-only
        echo "isort_failed=$?" >> $GITHUB_ENV

    # --- Main

    - name: Test results
      if: always()
      run: |
        passed=()
        failed=()

        echo "${{ env.pytest_failed }}"
        echo "${{ env.pytest_pyright }}"

        if [[ "${{ env.pytest_failed }}" != "0" ]]; then
          failed+=("pytest")
        else
          passed+=("pytest")
        fi

        if [[ "${{ env.pyright_failed }}" != "0" ]]; then
          failed+=("pyright")
        else
          passed+=("pyright")
        fi

        if [[ "${{ env.ruff_failed }}" != "0" ]]; then
          failed+=("ruff")
        else
          passed+=("ruff")
        fi

        if [[ "${{ env.isort_failed }}" != "0" ]]; then
          failed+=("isort")
        else
          passed+=("isort")
        fi

        if [ ${#passed[@]} -ne 0 ]; then
          echo "PASSED:"
          for check in "${passed[@]}"; do
            echo "    - $check"
          done
        fi

        if [ ${#failed[@]} -ne 0 ]; then
          echo "FAILED:"
          for check in "${failed[@]}"; do
            echo "    - $check"
          done
          exit 1
        fi
